---
title: "R Notebook"
output: html_notebook
---


```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(tidytext)
library(textdata)
#text_df1 <- read.delim("C:/Users/Sajid/Document/saci.txt")
#colnames(text_df1) = 'V1'
#text_df2 <- read.delim("C:/Users/Sajid/Documents/accuenture.txt")
#colnames(text_df2) = 'V1'
text_df3 <- read.delim("C:/Users/Sajid/Desktop/reports/ADP-10K.txt")
colnames(text_df3) = 'V1'
text_df4 <- read.delim("C:/Users/Sajid/Desktop/reports/Akamai 2020 Annual Report.txt")
colnames(text_df4) = 'V1'
text_df5 <- read.delim("C:/Users/Sajid/Desktop/reports/yirendri.txt")
colnames(text_df5) = 'V1'
text_df6  <- read.delim("C:/Users/Sajid/Desktop/reports/yelp.txt")
colnames(text_df6) = 'V1'
text_df7 <- read.delim("C:/Users/Sajid/Desktop/reports/yahoo.txt")
colnames(text_df7) = 'V1'
text_df8<- read.delim("C:/Users/Sajid/Desktop/reports/xo.txt")
colnames(text_df8) = 'V1'
text_df9 =  read.delim("C:/Users/Sajid/Desktop/reports/weyland.txt")
colnames(text_df9) = 'V1'
text_df10  <- read.delim("C:/Users/Sajid/Desktop/reports/virtusa.txt")
colnames(text_df10) = 'V1'
text_df11 =  read.delim("C:/Users/Sajid/Desktop/reports/vipshop.txt")
colnames(text_df11) = 'V1'
text_df12 = read.delim("C:/Users/Sajid/Desktop/reports/versign.txt", header=FALSE)
colnames(text_df12) = 'V1'
text_df13 = read.delim("C:/Users/Sajid/Desktop/reports/ultimate.txt", header=FALSE)
colnames(text_df13) = 'V1'
text_df14 = read.delim("C:/Users/Sajid/Desktop/reports/twcows.txt")
colnames(text_df14) = 'V1'
text_df15 = read.delim("C:/Users/Sajid/Desktop/reports/tech target.txt")
colnames(text_df15) = 'V1'
text_df16 = read.delim("C:/Users/Sajid/Desktop/reports/stamps.com.txt", header=FALSE)
colnames(text_df16) = 'V1'
text_df17 = read.delim("C:/Users/Sajid/Desktop/reports/spsc.txt", header=FALSE)
colnames(text_df17) = 'V1'
text_df18 = read.delim("C:/Users/Sajid/Desktop/reports/sitestar.txt", header=FALSE)
colnames(text_df18) = 'V1'
text_df19 = read.delim("C:/Users/Sajid/Desktop/reports/shutter stock.txt", header=FALSE)
colnames(text_df19) = 'V1'
text_df20 =  read.delim("C:/Users/Sajid/Desktop/reports/sfly.txt", header=FALSE)
colnames(text_df20) = 'V1'
text_df21 = read.delim2("C:/Users/Sajid/Desktop/reports/NASDAQ_ACXM_2018.txt", header=FALSE, comment.char="#")
colnames(text_df21) = 'V1'
text_df22 =  read.delim("C:/Users/Sajid/Desktop/reports/sabr.txt")
colnames(text_df22) = 'V1'
text_df23 = read.delim("C:/Users/Sajid/Desktop/reports/rdwr.txt")
colnames(text_df23) = 'V1'
text_df24 = read.delim("C:/Users/Sajid/Desktop/reports/ccrc.txt")
colnames(text_df24) = 'V1'
text_df25 = read.delim("C:/Users/Sajid/Desktop/reports/crm.txt", header=FALSE)
colnames(text_df25) = 'V1'
text_df26 = read.delim("C:/Users/Sajid/Desktop/reports/csod.txt")
colnames(text_df26) = 'V1'
text_df27 =  read.delim("C:/Users/Sajid/Desktop/reports/echo.txt", header=FALSE, comment.char="#")
colnames(text_df27) = 'V1'
text_df28 = read.delim("C:/Users/Sajid/Desktop/reports/dox.txt", header=FALSE)
colnames(text_df28) = 'V1'
text_df29 = read.delim("C:/Users/Sajid/Desktop/reports/cdw.txt", header=FALSE)
colnames(text_df29) = 'V1'
text_df30 = read.delim("C:/Users/Sajid/Desktop/reports/ebix.txt", header=FALSE)
colnames(text_df30) = 'V1'
text_df31 = read.delim("C:/Users/Sajid/Desktop/reports/call.txt")
colnames(text_df31) = 'V1'
text_df32 = read.delim("C:/Users/Sajid/Desktop/reports/EIGI.txt")
colnames(text_df32) = 'V1'
text_df33 = read.delim("C:/Users/Sajid/Desktop/reports/EVLV.txt")
colnames(text_df33) = 'V1'
text_df34 = read.delim("C:/Users/Sajid/Desktop/reports/GOOG.txt")
colnames(text_df34) = 'V1'
text_df35 = read.delim("C:/Users/Sajid/Desktop/reports/GSB.txt")
colnames(text_df35) = 'V1'
text_df36 = read.delim("C:/Users/Sajid/Desktop/reports/grub.txt", header=FALSE)
colnames(text_df36) = 'V1'
text_df37 =read.delim("C:/Users/Sajid/Desktop/reports/FLWS.txt") 
colnames(text_df37) = 'V1'
text_df38 = read.delim("C:/Users/Sajid/Desktop/reports/CHKP.txt")
colnames(text_df38) = 'V1'
text_df39 =  read.delim("C:/Users/Sajid/Desktop/reports/GDDY.txt")
colnames(text_df39) = 'V1'
text_df40 = read.delim2("C:/Users/Sajid/Desktop/reports/IAC.txt")
colnames(text_df40) = 'V1'
text_df41 = read.delim("C:/Users/Sajid/Desktop/reports/eqix.txt")
colnames(text_df41) = 'V1'

df = rbind(text_df3,text_df4,text_df5,text_df6,text_df7,text_df8,text_df9,text_df10,
           text_df11,text_df12,text_df13,text_df14,text_df15,text_df16,text_df17,text_df18,
           text_df19,text_df20,text_df21,text_df22,text_df23,text_df24,text_df25,text_df26,
           text_df27,text_df28,text_df29,text_df30,text_df31,text_df32,text_df33,text_df34,
           text_df35,text_df36,text_df37,text_df38,text_df39,text_df40,text_df41)
dd <- df %>%
  # Tokenization
  unnest_tokens(word, V1) %>%
  # Remove Stop Words
  anti_join(get_stopwords())


dd %>%  
  count(word, sort = TRUE)

snts<- get_sentiments("loughran")
# get POSITIVE words
positive <- get_sentiments("loughran") %>%
  filter(sentiment == "positive")
# get NEGATIVE words
negative <- get_sentiments("loughran") %>%
  filter(sentiment == "negative")

# count positive words
count_positive <- dd %>%
  semi_join(positive) %>%
  count(word, sort = TRUE)

# count negative words
count_negative <-dd %>%
  semi_join(negative) %>%
  count(word, sort = TRUE)
head(count_positive)
head(count_negative)

# get uncertainty words
uncertainty <- get_sentiments("loughran") %>%
  filter(sentiment == "uncertainty")

# count uncertain words
count_uncertain <- dd %>%
  semi_join(uncertainty) %>%
  count(word, sort = TRUE)

# get litigious words
litigious <- get_sentiments("loughran") %>%
  filter(sentiment == "litigious")

# count uncertain words
count_litigious <- dd %>%
  semi_join(litigious) %>%
  count(word, sort = TRUE)

sd = count_positive[order(-count_positive$n),]
sd = sd[1:20,]

ds = count_negative[order(-count_negative$n),]
ds = ds[1:20,]

fd = count_uncertain[order(-count_uncertain$n),]
fd = fd[1:20,]

gf = count_litigious[order(-count_litigious$n),]
gf = gf[1:20,]


x=ggplot(sd,aes(x=reorder(word, n),y=n))+geom_col()+coord_flip()+ggtitle("Top twenty positve words") +xlab("Number of words")+ylab("Words")
xx=ggplot(ds,aes(x=reorder(word, n),y=n))+geom_col()+coord_flip()+ggtitle("Top twenty negative words") +xlab("Number of words")+ylab("Words")
xxx=ggplot(fd,aes(x=reorder(word, n),y=n))+geom_col()+coord_flip()+ggtitle("Top twenty uncertain words")+xlab("Number of words")+ylab("Words")
xxxx=ggplot(gf,aes(x=reorder(word, n),y=n))+geom_col()+coord_flip()+ggtitle("Top twenty litigious words")+xlab("Number of words")+ylab("Words")

```
```{r}
ggplot(sd,aes(x=reorder(word, n),y=n))+geom_col()+coord_flip()+ggtitle("Top twenty positve words")+xlab("Number of words")+ylab("Words")
ggplot(ds,aes(x=reorder(word, n),y=n))+geom_col()+coord_flip()+ggtitle("Top twenty negative words")+xlab("Number of words")+ylab("Words")
ggplot(fd,aes(x=reorder(word, n),y=n))+geom_col()+coord_flip()+ggtitle("Top twenty uncertain words")+xlab("Number of words")+ylab("Words")
ggplot(gf,aes(x=reorder(word, n),y=n))+geom_col()+coord_flip()+ggtitle("Top twenty litigious words")+xlab("Number of words")+ylab("Words")
```

```{r}
require(gridExtra)
#lay <- rbind(c(1,2),
#c(3,3))
grid.arrange(x, xx, ncol=2 , layout_matrix = rbind(c(1,2)))
```

```{r}
require(gridExtra)
#lay <- rbind(c(1,2),
#c(3,3))
grid.arrange(xxx, xxxx, ncol=2 , layout_matrix = rbind(c(1,2)))
```
